# Generated by Django 5.1.4 on 2025-01-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celleryworker', '0003_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
