# Generated by Django 5.1.4 on 2025-01-05 17:59

import celleryworker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celleryworker', '0004_alter_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='messages/', validators=[celleryworker.models.file_validator]),
        ),
    ]
